### ISSUE TITLE
Improve the Format of the Output of the Generated Groups

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#1]
Currently, the output of the group formation process displays the group number and then all of the student identifiers in a single list. However, this formatting of the output will not look very good if the groups are large and/or if the student identifies are long. The output should be formatted so that it supports vertical, instead of horizontal, scrolling of the listed groups.

**Comment by sutterj** [comment]
If we are going to use categories to sort the teams, would these need to be listed and if so, how should they be displayed?

**Comment by dillam** [comment]
The output has been reformatted so that it is vertical instead of horizontal.
