### ISSUE TITLE
Perform Linting and Improve the Program's Source Code

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#10]
Currently, parts of the program may not fully adhere to the standards set by PEP8. It would be great if the source code was input into a linting tool and all of the offending lines of code were improved. If possible, there should be a program that can automatically perform linting and display the problems to a developer. Finally, it might be a good idea to integrate linting with [pytest](https://github.com/tholo/pytest-flake8).

**Comment by lylet-AC** [comment]
**Linting:** any tool that flags suspicious usage in software written in any computer language.

**flake8** is a tool that automatically collects "lint" when you run pytest with the `--flake8` tag in the command line.  Ex.) `pytest tests --flake8`

**Goal:** Integrate flake8 into the testsuite so running the testsuite will flag PEP8 violations.

**Comment by bristola** [comment]
We will use the pytest-flake8 library.  It may be possible to just directly use the python files that the github repository supplies, and then use the classes and methods in that python file in the test suite implementation.
https://github.com/tholo/pytest-flake8

**Comment by lylet-AC** [comment]
How to test our test cases: run a faulty code that will not pass PEP8 standards, then double check with code that will pass PEP8 standards.

**Comment by bristola** [comment]
If you `pip install pytest-flake8`, you also install the flake8 api that can be used in any python file.  By using `from flake8.api import legacy as flake8` in a python file, you can use various classes and functions in the flake8 library including the `check_files(file_name)` function which will perform linting checks on the input file.  We could possibly use this to integrate linting in the test suite.

**Comment by bristola** [comment]
http://flake8.pycqa.org/en/latest/user/python-api.html
Website for the flake8 api.

**Comment by burrowss** [comment]
How is the linting coming along for the source code? Are you able to go through it yet and make sure everything is correct? @bristola

**Comment by bristola** [comment]
@burrowss Yes, Tyler and I just worked on our task in Alden for a while and got things mostly working on our branch.  We added our own file on our branch called *linting.py*, and if you run `pytest linting.py` it will run a test case to check PEP8 standards.  It will print out all cases found in all python files in the *gatorgrouper* directory where the files do not adhere to PEP8 standards.  We also added to the *README* an installation requirement for *flake8*.  Now, all we need to do is wait for the test suite so we can add our code into that file as another test case.  I don't know if we have to fix all the PEP8 problems in the existing code because after running our test there seems to be a lot.

**Comment by bristola** [comment]
How do we plan on implementing this linting test into master? After running our linting tests, there are a lot of problems in the code where it does not adhere to PEP8.  Will we fix all the PEP8 problems pointed out by our test case after the final implementation of the code is pushed to master?

**Comment by burrowss** [comment]
Yeah, there looks to be a tool called autopep8 so I'm going to see if we might be able to use that so we don't have to go through every line of code and fix the errors.

**Comment by burrowss** [comment]
It looks like the linting file right now goes through everything including site-packages and stuff that isn't written for our project. Can you take a look at that and make sure that it's running through files that we are supposed to change and keep track of? Like the py files just in our repository

**Comment by bristola** [comment]
I just added the functionality to check for PEP8 in subdirectories.  Here's the link for library that automatically fixes of PEP8 problems that @burrowss was talking about. https://github.com/hhatto/autopep8

**Comment by bristola** [comment]
Are there any PEP8 standards that we should ignore when linting?

**Comment by burrowss** [comment]
Linting has now been performed on all of the code and additionally is part of the test suite. Instructions on further linting have also been added to the readme in case any issues arise.
