### ISSUE TITLE
Integrate Travis CI Using the Free Version Available for Open-Source Projects

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#11]
After a test suite exists and linting is fully integrated, in fulfilment of Issue #3 and Issue #9 and Issue #10, the entire system should be integrated with Travis CI, which is freely available to open-source projects. This will ensure that it is possible to run the test suite and the linting tools whenever code is committed.

**Comment by bristola** [comment]
After the our linting test case is integrated with the test suite, it will require `pip install pytest-flake8` in order to run correctly with Travis Cl.

**Comment by Andre-Bryan** [comment]
where is the .travis.yml?

**Comment by Andre-Bryan** [comment]
need admin rights to integrate with travis ci

**Comment by colezAC** [comment]
I'm waiting on the testing suite before adding Travis. I have a branch with everything set up, just need the test suite before merge.
