### ISSUE TITLE
Support Marking Students as Absent So As to Avoid Group Assignment

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#12]
Currently, the program assumes that all students will be available for every possible group project. However, if a student has been temporarily excused from the course and/or is away from campus, then it would be ideal to exclude that student from the automatically generated groups. This will ensure that the students are not assigned to teams with which they will never be able to contribute.

**Comment by mendezjw** [comment]
Tasks:
- Ask the user for input of who is absent
- Assign variables to each member
- Remove absent members and print out list
- Testing the function after it is implemented using test suites

**Comment by TravisThomasAC** [comment]
As of now the requirements are not unambiguous. We need to know what input will be asked from the user and how user input will be accepted in order to complete the task of removing missing students from the potential groups.

**Comment by millinj2** [comment]
The requirements are not complete. We need to know the input and how that input will be used. We also should clarify if the user would like to know if the student was excused from the assignment or if they were unexcused.

**Comment by TravisThomasAC** [comment]
The first implementation for this issue is complete. Needs to merged with master to ensure correctness and to see if any changes need to be made.

**Comment by millinj2** [comment]
So I guess Maria did not add in a command line argument to read in the list of lists of student for out function. @TravisThomasAC can you find a way to do this? We have to get back to Nick in issue 3 for the function call to the lists.

**Comment by millinj2** [comment]
Just adding documentation for discussion through Slack on Wednesday October 11.

> mendezj [10:37 PM] 
> issue #12 needs to: take from the csv a list of list and the list of people absent from the command line provided by the user(professor), search through the list of list to find any individual list of lists(peoples names) and output a list by taking names of people absent and removing them.
> 
> mendezj [10:42 PM] 
> I need this by 7pm saturday because issue 2 and 10 are dependent on this and we need to give them enough time to complete their tasks. This time was established by the project managers.
> 
> [10:42] 
> Please let me know if there are any issues or need me to clarify.

> mendezj [4:40 PM] 
> @U6X30LJH5 @thomast2 Hey can you guys respond to issue 3 with the inputs and outputs as well as the function’s behaviors for issue 5 so Dan’s team can write the test cases for it. Just follow the layout Maria already posted in issue 3’s comments in the issue tracker.
> [4:44] 
> @geerc The general foundation of tox is there and it runs through and outputs which environments causes errors if there are any or if a specific version of python is not installed. This should allow you to get started on the readme file. When I start going through files in gatorgrouper I am getting errors so I’ll try to have those fixed by tonight. (edited)
> 
> millinj2 [6:02 PM] 
> I just posted the inputs and outputs for issue 12

We met Thursday October 12 to discuss this issue. Maria was brought in to help clarify the exact requirement of this issue. The code was then implemented and push to the correct branch for a pull request.

**Comment by delgrecoj** [comment]
merged into master.
