### ISSUE TITLE
Support Running the Test Suite in a Parallel Manner

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#15]
While the program currently does not have a test suite, Issue #3 requests one. However, it is possible that this test suite will be larger and more costly to run as features are added to the system. As such, it may be a good idea to investigate the use of [xdist](https://pypi.python.org/pypi/pytest-xdist) for running the test suite in parallel. If this improves the performance of testing, then this feature should be document according to the standards mentioned in Issue #9.

**Comment by burrowss** [comment]
Can test to see if its an improvement by timing the test cases without xdist, and then after implementation of it. If it improves, then it can be added to the documentation/standards.

**Comment by burrowss** [comment]
There are multiple different usages of xdist, so we will test each case to try and find the most efficient one to use

**Comment by karolvargas** [comment]
It seems as though Python3 does not support -xdist so we will continue to look for more methods to run      -xdist

**Comment by burrowss** [comment]
After extensive testing with our test suite, we found that it is faster to just run the standard pytest tests instead of running the suite in parallel. Due to this, we have decided not to implement this issue and will instead keep the original pytest tests
