### ISSUE TITLE
What is the "Best" Way to Automatically Assign Students to Groups?

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#16]
All of Issues #1 through #15 assume that there is a "best" was to automatically assign students to groups. However, it is worth discussing what this "best" way might look like? How can we automatically assign students to groups so as to ensure that they work [effectively as teams](http://www4.ncsu.edu/unity/lockers/users/f/felder/public/Papers/Oakley-paper(JSCL).pdf)?

**Comment by yeeunmariakim** [comment]
Our system has the ability to distribute students evenly among groups by the skills they indicate they have (via Google Forms). These skills are represented as boolean values, not on a Likert-like scale. We hope that this algorithm allows for groups that are composed of individuals with a range of strengths; however, we are unsure of its performance (i.e. whether it creates better groups) than randomly creating groups, which is the default behavior of this program.
