### ISSUE TITLE
Verify the Command-Line Arguments

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#2]
Currently, the program only provides command-line argument verification as is provided by default with the `argparse` library. As such, it might be useful to add more command-line verification. For instance, it might be useful to check that the size for the number of members in a group is within a suitable bounds. As an example, it would not make sense to request a group size that is greater than the number of students in the course. Moreover, it also would not be a good idea for the groups size to be close to the number of students in the course. Is there a way to set and check some reasonable bounds for these parameters?

**Comment by shafferz** [comment]
Going to investigate the ways a Python program can read command-line arguments, and will investigate ways to set boundaries for them as well.

**Comment by castellanosr** [comment]
Currently investigating the argparse library so that we will know what it is lacking and, therefore what we can add in order to improve the command-line verification. I am also looking at how to set bounds.

**Comment by castellanosr** [comment]
This is slightly ambiguous because there in not much instruction on what checks are necessary. We should check to make sure the group size does not exceed the number of the people in our class and does not approach it. However, what else do we need? This is something we should ask the customers about so that we ensure the product fulfils their desires.

**Comment by castellanosr** [comment]
Upon speaking with the customer, we have learned that the two afore mentioned checks (group not exceeding class number or getting too close) are the only necessary checks unless other teams implement more features that need checking (referencing a google sheet, for example).

**Comment by milleriAC** [comment]
Here is a good website to have a better understanding of how argparse works in python:
 [https://docs.python.org/3.3/library/argparse.html]({Python Documentation for Argparse)

**Comment by castellanosr** [comment]
Would we be able to simply use if statements for our checks or do we need to do a more complicated argparsing version (look at past two labs)?

**Comment by castellanosr** [comment]
Last night @milleriAC and I implemented a few checks. We added an if statement to check and see if the group size was at least half the class size and to make sure the class size was at least one. As it is currently written the code will check and if the check fails a print statement will be displayed stating "invalid arguments" and the program will quit. @gkapfham as the customer, is this what you would like to see? Or would you prefer the error message to be more descriptive/for the program not to quit?

**Comment by yeeunmariakim** [comment]
@milleriAC @castellanosr how is making the revisions I suggested in the pull request going?

**Comment by castellanosr** [comment]
@yeeunmariakim I just made the requested revisions. Will you look over them again and let me know how it looks?

**Comment by castellanosr** [comment]
The moved logic I moved is now incomplete. We need to read the list because it does not exist yet in the parse_gatorgrader_arguments.py.

**Comment by shafferz** [comment]
Hey @castellanosr and @milleriAC, I just read the code on the Pull Request that you've put up. I think I have an idea that will successfully implement our parse_gatorgrouper_arguments.py successfully, utilizing the read_student_file.py to use the code that you've already written, and to fix the gatorgrouper.py to also successfully make the revisions that @yeeunmariakim requested. I also discussed with Maria getting our implementations done as soon as possible, and she suggested that we try to complete the code by Friday evening. This will allow us time to implement changes that are necessary as a result of unforeseen dependencies on other issues.

I can open a branch and make changes to the code myself, if you'd both be okay with that. Alternatively, we can meet in person some time? I'm free on Thursdays after 8pm, Friday evenings after 5pm, and any time we may be able to work out on the weekend.

**Comment by castellanosr** [comment]
@shafferz and I worked for over an hour trying to move the verification logic into the parse_gatorgrader_arguments.py but it did not work because of the order in which information is gained. The logic must stay where @milleriAC and I put it.

**Comment by yeeunmariakim** [comment]
@shafferz @castellanosr @milleriAC I moved the logic to the `parse_gatorgrouper_arguments.py` file (formerly named `parse_gatorgrader_arguments.py` without obstacle. That move has been merged into the issue 2 feature branch, which is currently under review in a pull request to be merged into master.

**Comment by yeeunmariakim** [comment]
closing this issue because the check for group size has been merged into master in pull request #35
