### ISSUE TITLE
Repository Contains Derived Files

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#20]
The repository now contains a `gatorgrouper/__pycache__/` directory. If I understand correctly, this is a derived directory that does not need to be under version control. Should this directory be deleted?

**Comment by sutterj** [comment]
My request was not yet merged into master.  The cache files were apart of merge #17 and #18.  They are also included in my commit, but it has not yet been merged.

**Comment by delgrecoj** [comment]
This has been done (and added to a `.gitignore` file) in our branch for issue #13, as of this morning... for what that's worth.  Gotcha is that you have to remove the directory and commit that first before gitignoring it.

**Comment by delgrecoj** [comment]
After some slight changes, the pull request received three approvals from project managers and was merged into master, so closing this issue.
