### ISSUE TITLE
student_identifers to student_identifiers - refactoring/bettering code

### ISSUE THREAD

**Issue by castellanosr** [GatorGrouper/gatorgrouper#31]
The variable student_identifers is spelled wrong - it is missing an i. I spoke to @gkapfham about this and he instructed me to make a new issue and a branch to fix it.

**Comment by castellanosr** [comment]
I just finished adding the missing "i"s. I believe that this will make the code easier to read and especially easier to edit. I also noticed that "gatorgrader" is written in a few places instead of "gatorgrouper" but I do believe that someone else already pointed this out. Is this issue being addressed?

**Comment by delgrecoj** [comment]
merged.
