### ISSUE TITLE
Test and Document the Intended Execution Environment

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#5]
Currently, the `README.md` file does not explain the details of the execution environment in which the program can execute. As such, it would be a good idea to test this program in multiple execution environments and then document what does and does not work correctly. For instance, it may be a good idea to use the [Tox Testing Tool](https://github.com/tox-dev/tox) to support the completion of this task. Ultimately, it would be great if the tool is demonstrably useful on a wide variety of execution environments and this was documented in the `README.md` file.

**Comment by mendezjw** [comment]
Tasks
- Use Tox Testing Tool to test code in multiple execution environments
- Document outcomes from testing in multiple environments and the environments that were used.

**Comment by mendezjw** [comment]
As of the current moment, the program is testable in multiple environments, however it would not be beneficial with the software being in such an alpha stage and how drastically different it could become in the coming weeks.

**Comment by mendezjw** [comment]
After consulting the customer, we came to a consensus that the requirements for this issue will also need to include the configuration of tox to successfully run the software in different execution environments. If the test fails in a specific environment, we will need to determine if the configuration of tox has caused the issue or if the issue was caused by another team and inform them that a fix may be needed.

**Comment by mendezjw** [comment]
After many attempts to get the tox testing tool working, the project managers as a collective deemed that there was to little documentation for the files needed in tox to successfully get a working testing tool with the allotted time. With the given documentation, provided by https://tox.readthedocs.io, we would need to look in every tox file and figure out how it would correlate to the files of GatorGrouper. Until we can look into this issue further, we can only confirm GatorGrouper runs in Python 3.5 .

**Comment by geerc** [comment]
Added into the read.me information about the tox testing tool.
