### ISSUE TITLE
Add Usage Examples to the Documentation

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#6]
Currently, the `README.md` file does not furnish any examples of how the program is run on the command-line. Additionally, the documentation does not explain the input or output of the program. Each of the key ways in which the program can be executed must be documented in the `README.md` file so that people can clearly understand all of the features that the tool provides. In particular, this issue should be resolved in light of Issue #13 and Issue #14.

**Comment by sutterj** [comment]
What all are we anticipating as input?  The input and output is totally dependent on how the system functions.  Without knowing eveything that the user could do with the program, there is no way to document the input and output and commands.

**Comment by yeeunmariakim** [comment]
@sutterj issue #2 is dependent on the issue #12, issue #13, issue #14 as well. once they are finished with their implementations, they should let both @sutterj and me know what command line arguments they need

**Comment by yeeunmariakim** [comment]
@sutterj we'll let you know the levels of diagnostic output flags that we end up implementing once we have completed issue #4

**Comment by delgrecoj** [comment]
@sutterj please see our issue #13 for what we're expecting as input, although note that #14 will most likely break our implementation, which was why our group wanted both of those issues.  Arguments used will be listed clearly in the code, once we finish the implementation.

**Comment by sutterj** [comment]
I created a branch for this issue.  Now my group is just waiting for the inputs and outputs of the program to be decided.

**Comment by sutterj** [comment]
We will update the README to include the structure and description of the sorting algorithms in addition to explaining to the user how to use the program.  We will document the way in which we expect the user to use the program.

**Comment by sutterj** [comment]
These are the items that should be included as documentation in the README.  The items with ?'s beside them are things that we have to decide if they should be included as documentation.  If you could list in this issue some details about the work you have done, my team can then begin updating the README with all the necessary information.

Command Line Arguments #2 
Document the arguments that the user will use in the command line.

Run Test Suite #3 #9 
Document how to run the test suite.  There is a group assigned to this already, but I want to make sure that it gets organized with all the other items that have to go in the README.

Program Usage #6
Document how the user will use the program.  Describe what the expected inputs and outputs will be.  This will depend on how #12 #13 and #14 are implemented.

Logging? #4 
List how the logging is done and what the user should expect to see.

Test Suite Coverage? #8 
Describe the coverage of the test suite and how this was determined (Coveralls).

Execution Environment #5 
List what environments the program can be run in.

Integrate Linting? #10 
If linting is integrated, describe the process.

Travis CI #11 
Describe Travis CI.

Parallel Test Suite? #15 
If this is completed, document the process and describe how performance was improved.


Let me know if there are any questions or anything that you would like to add or change.

**Comment by yeeunmariakim** [comment]
Here is some usage documentation related to Issue #2:

To specify the size of groups, use the flag `--group-size`. For instance, `python3 gatorgrouper.py --group-size 3` indicates that groups should each contain 3 members. The group size should be greater than 1 and equal to or less than half the total number of students.

**Comment by yeeunmariakim** [comment]
Here is some usage documentation related to issue #4:

To see a detailed general output from the program to monitor its progress, use the flags `-v` or `--verbose`. 
Example: `$ python gatorgrouper.py --verbose`

To see a detailed technical output from the program to diagnose issues, use the flag `-d` or `--debug`. 
Example: `$ python gatorgrouper.py --debug`

If none of the `-v`, `--verbose`, `-d`, `--debug` flags are used, then logging will be shown only when an error occurs.

**Comment by yeeunmariakim** [comment]
Here is usage documentation related to issue #13:

To group students randomly, use the `--random` flag.
Example:  `$ python3 gatorgrouper.py --random`

To group students using the sudoku method, use the `--sudoku` flag.
Example: `$ python3 gatorgrouper.py --sudoku`

To group students using the round-robin method, use the `--round-robin` flag.
Example: `$ python3 gatorgrouper.py --round-robin`

If none of these flags are used, then the random grouping method will be used.

**Comment by yeeunmariakim** [comment]
Here is usage documentation related to issue #12:

To indicate absent students, use the `--absentees` flag followed by the list of absent students. This flag can be used in the following ways:
`$ python3 gatorgrouper.py --absentees yeeunmariakim, delgrecoj`
`$ python3 gatorgrouper.py --absentees 'yeeunmariakim', 'delgrecoj'`
`$ python3 gatorgrouper.py --absentees "yeeunmariakim", "delgrecoj"`
`$ python3 gatorgrouper.py --absentees yeeunmariakim delgrecoj`
`$ python3 gatorgrouper.py --absentees 'yeeunmariakim' 'delgrecoj'`
`$ python3 gatorgrouper.py --absentees "yeeunmariakim" "delgrecoj"`

**Comment by yeeunmariakim** [comment]
Here is usage documentation about a command line argument that already existed:

To name the file in which the list of students to group is contained, use the `--students-file` flag.
Example: `$ python3 gatorgrouper.py --students-file "students_list.txt"` or `$ python3 gatorgrouper.py --students-file students_list.txt`

If a file name is not specified, then the file name is assumed to be "students.txt".

**Comment by sutterj** [comment]
@yeeunmariakim and @delgrecoj could you explain how the sudoku and round-robin methods will work so that they can be described in the README?

**Comment by delgrecoj** [comment]
Round robin will go through each of the groups adding one student each time until no students are left... don't have specifics on how it's choosing which student each time because I keep getting pulled away from working on this for other things, but it will try and do so in a way that diversifies the groups as best as possible.

Named the sudoku method that because the approach I want to use there is one based on sudoku solvers, but there are numerous approaches there and I haven't yet gotten to it, so I don't have any information for you there.

**Comment by delgrecoj** [comment]
once they're implemented there will be explanatory comments that should be of use for the `README`.

**Comment by eltmanm** [comment]
I'm in the process of writing a chunk of text to explain how to prepare to run the program for the first time based around the Google sheets implementation from #14. I will paste it as a message in here once it is complete, as I am currently working from my laptop which doesn't have many of the required tools for sending it as a file on here and don't have time at the moment to get it that way.

**Comment by wojnarn** [comment]
I'm in the process of adding examples and documentation for the specification and the round robin

**Comment by sutterj** [comment]
@wojnarn @JattMones Please add the parts that I assigned you by today at 1:30.  Make a branch off the branch for issue #6 and make a pull request so that I can review it.

**Comment by wojnarn** [comment]
@sutterj I made a separate branch for my own assignment, was it not off of this branch?

**Comment by sutterj** [comment]
It should have been off of 6 and not off the master.

**Comment by eltmanm** [comment]
[Steps to Setup GatorGrouper for first time use.docx](https://github.com/GatorGrouper/gatorgrouper/files/1388463/Steps.to.Setup.GatorGrouper.for.first.time.use.docx)
this is a docx file, will need to be put into the readme or otherwise for final launch. someone will also need to look over it.

**Comment by sutterj** [comment]
@eltmanm I put your instructions in the readme on the branch for 6.

**Comment by sutterj** [comment]
merged
