### ISSUE TITLE
Travis CI build Failing Because of Gspread

### ISSUE THREAD

**Issue by yeeunmariakim** [GatorGrouper/gatorgrouper#62]
The Travis build is failing because of the following error.
```
_________________ ERROR collecting tests/test_gatorgrouper.py __________________
ImportError while importing test module '/home/travis/build/GatorGrouper/gatorgrouper/tests/test_gatorgrouper.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_gatorgrouper.py:7: in <module>
    import gatorgrouper
gatorgrouper.py:15: in <module>
    from spreadsheet import create_csv
spreadsheet.py:1: in <module>
    import gspread
E   ImportError: No module named 'gspread'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
```
I think this could be fixed by adding this command to the `travis.yml` document.
`python3 -m pip install --user gspread oauth2client`

@Andre-Bryan could you look at resolving this issue?

**Comment by Andre-Bryan** [comment]
I put that in already but it didnt work because it said that it cant be installed in virtually in travis
thats why I slacked kapfhammer

**Comment by Andre-Bryan** [comment]
`$ python3 -m pip install --user gspread oauth2client
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
The command "python3 -m pip install --user gspread oauth2client" failed and exited with 1 during .'

**Comment by Andre-Bryan** [comment]
tried - python3 -m pip install gspread oauth2client got the same error

**Comment by Andre-Bryan** [comment]
everything should work now
