### ISSUE TITLE
Test suite not running

### ISSUE THREAD

**Issue by sutterj** [GatorGrouper/gatorgrouper#65]
The test suite will not run.  I edited some of the commands in the readme for installing the requirements for the test suite to include `--user`.  I made pull request #64 for this.  I am not sure about the test suite though.  Is anyone else having any issues?

**Comment by burrowss** [comment]
I just ran it perfectly fine

**Comment by sutterj** [comment]
I tried it on my computer and a lab computer and I could not get it to run after ensuring I had all the requirements installed
