### ISSUE TITLE
Refactor the Source Code by Moving Functions to New Files

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#7]
Currently, the functions for shuffling a list of students and grouping the students are in the same file as the one that provides the main user interface. Instead, it would be better if these functions are moved into separate files. Going forward, this will be particularly useful since we may want to add new mechanisms for shuffling the list of students or grouping the students. Finally, it is worth noting that there should be test cases to demonstrate that this refactoring worked correctly.

**Comment by ZachAndrews98** [comment]
Merged into master working refactor. Kept open for any comments on refactoring.

**Comment by delgrecoj** [comment]
Initial refactoring completed.
