### ISSUE TITLE
Absentees not working for multiple people

### ISSUE THREAD

**Issue by burrowss** [GatorGrouper/gatorgrouper#70]
python3 gatorgrouper.py --absentees kimy, burrowss

outputs 

GatorGrouper: Automatically Assign Students to Groups
https://github.com/gkapfham/gatorgrouper

Group 1
dillam
colez
millinj2

Group 2
kimy
eltmanm
bonnettd

Group 3
thomast2
kimy
toccin

Group 4
sutterj
bristola
lylet

Group 5
delgrecoj
luoman
shafferz

Group 6
mendezj
vargask
cerdamejiaj

Group 7
bryana
wojnarn
andrewsz

kimy is still there so absentee is not working properly

**Comment by sporrera** [comment]
Going off of this, the flags that do NOT work are:
python3 gatorgrouper.py --absentees student1, student2 
     **student1 is still placed in a group
python3 gatorgrouper.py --absentees 'student1', 'student2'
     **student1 is still placed in a group
python3 gatorgrouper.py --absentees "student1", "student2"
     **student1 is still placed in a group

**Comment by millinj2** [comment]
This also cannot take in two commands such as --absentees and --group-size. It does not specify the absentees and group size to get the specific groups needed with the correct students.

**Comment by burrowss** [comment]
So everything seems to be working on an old branch Maria made, called feature/fixing-absentee-bug. If we can use the old code from that, and implement it, it should be able to work correctly

**Comment by burrowss** [comment]
I've been checking this issue, and it seems like once spreadsheets.py and gatorgrouper.py are edited to include the defaults, it starts to fail. I'm going to continue looking into changing up the defaults so it works.

**Comment by eltmanm** [comment]
in case this much has not been figured out yet, Shaffer and I have been taking a look at this for GUI, and it appears absentees is taking exclusively the last name entered.

**Comment by burrowss** [comment]
So I think the issue was me using it on git bash on Windows because while it was failing there, on my laptop with Ubuntu it works fine. So I'm not quite sure if there is an issue with the code

**Comment by lylet-AC** [comment]
I'll try it out on my windows pc too to see if it's working

**Comment by mendezjw** [comment]
I also noticed that there are two kimy and when a working command line input is used both kimy are removed from the groups, which can cause issues for people with the same name.

- In burrowss example output there is a kimy in groups 2 & 3

**Comment by burrowss** [comment]
@mendezjw it shouldn't be an issue since allegheny emails are different for everyone. One email would have a 2 at the end of it and the program checks the name before the @ symbol which is unique. The reason why there are 2 kimy is that Maria entered responses twice

**Comment by millinj2** [comment]
@mendezjw @burrowss Yes this is addressed in issue #75, so it should take the most recent entry from the spreadsheet and use that to make the groups.

**Comment by burrowss** [comment]
Since this is being addressed somewhere else and the original issue has been dealt with, I'm going to close the issue
