### ISSUE TITLE
Potential Help argument

### ISSUE THREAD

**Issue by burrowss** [GatorGrouper/gatorgrouper#71]
Similar to Accelegator, maybe we can add a help argument where it prints out the possible arguments that can be entered

**Comment by ZachAndrews98** [comment]
This is essentially already accomplished by typing 
> python3 gatorgrouper.py -h
unless you are saying we implement a command system like Accelegator's and have commands typed into the program when it is running instead of before.

**Comment by ZachAndrews98** [comment]
This is essentially already accomplished by typing 
> python3 gatorgrouper.py -h
unless you are saying we implement a command system like Accelegator's and have commands typed into the program when it is running instead of before.

**Comment by ZachAndrews98** [comment]
This is essentially already accomplished by typing 

> python3 gatorgrouper.py -h

Unless you are saying we implement a command system like Accelegator's and have commands typed into the program when it is running instead of before.

**Comment by ZachAndrews98** [comment]
This is essentially already accomplished by typing 

> python3 gatorgrouper.py -h

Unless you are saying we implement a command system like Accelegator's and have commands typed into the program when it is running instead of before.

**Comment by burrowss** [comment]
That is what I mean, but it looks like we don't have that in the README, we should add that
