### ISSUE TITLE
Feature Number of Groups

### ISSUE THREAD

**Issue by millinj2** [GatorGrouper/gatorgrouper#72]
Add the feature to select the number of groups, like group size, for randomization.

**Comment by millinj2** [comment]
Made a branch called i-72-num-of-groups. Also started a parse arugment for this feature.

**Comment by ZachAndrews98** [comment]
How do we determine what should take priority when grouping students- group size or number of groups? Do we want it to be that if the number of groups is different than the default value, the number of groups takes priority or something else?

**Comment by toccinAC** [comment]
I agree the number of groups should take priority if the number is different from the default value.

**Comment by ZachAndrews98** [comment]
I implemented this feature, as I stated above if the number of groups is not the default (0, to not allow people to troll the system by having group sizes of 0) then the number of groups will be fixed at the user's input and place all of the students into these groups. I will create a pull request for it but please run the code and look for any bugs that I may have missed.

**Comment by millinj2** [comment]
I ran it and it looks good!

**Comment by millinj2** [comment]
@ZachAndrews98 where exactly is the code for this?

**Comment by millinj2** [comment]
Also I just pushed the test case for this feature. The tests pass except for the flake8. Not sure if this is just because I need to install something or what. @burrowss

**Comment by ZachAndrews98** [comment]
@millinj2 The functions for this feature are in group_random and group_rrobin.
