### ISSUE TITLE
Move default items to DEFAULTS.py

### ISSUE THREAD

**Issue by eltmanm** [GatorGrouper/gatorgrouper#73]
Items in the program such as default group size should be entered into a default file so that users have better access and changeability to what their default configurations would be. we have one called defaults.py, but given someone who does not have access to editing python or what not, a .txt file would perhaps be a better idea.

**Comment by burrowss** [comment]
I think the defaults.py is fine since you can edit it like a txt file if needed and it already has the defaults needed
