### ISSUE TITLE
Form Response Editing

### ISSUE THREAD

**Issue by millinj2** [GatorGrouper/gatorgrouper#75]
When a student edits their response in the Google Form, their name ends up in the csv file twice (or more depending on the number of times they edit their response). There needs to be a way that pulling from the csv file will only take the most recent response in the spreadsheet from the student.

**Comment by millinj2** [comment]
@dillam would this be implemented in the speadsheet.py with pulling from the google sheets?

**Comment by dillam** [comment]
You can also just make it so that the google form will not let you edit your answers. But yes it would be done in `spreadsheet.py`. Lines 34-48 are for making sure that the output from the google form is int the proper format.

**Comment by dillam** [comment]
You can also just make it so that the google form will not let you edit your answers. But yes it would be done in `spreadsheet.py`. Lines 34-48 are for making sure that the output from the google form is int the proper format.

**Comment by dillam** [comment]
You can also just make it so that the google form will not let you edit your answers. But yes it would be done in `spreadsheet.py`. Lines 34-48 are for making sure that the output from the google form is int the proper format.

**Comment by dillam** [comment]
You can also just make it so that the google form will not let you edit your answers. But yes it would be done in `spreadsheet.py`. Lines 34-48 are for making sure that the output from the google form is int the proper format.

**Comment by millinj2** [comment]
@dillam have you worked on this at all?
