### ISSUE TITLE
Calculate and Report the Coverage of the Test Suite

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#8]
Currently, there is no test suite for this program. However Issue #3 requests the creation of a test suite. Once this test suite is created, it would be a good idea to ensure that the tests have good coverage. It would be a good idea to look into a package like [pytest-coverage](http://pytest-cov.readthedocs.io/en/latest/) to complete this tasks. Would this [tutorial](http://www.robinandeer.com/blog/2016/06/22/how-i-test-my-code-part-3/) provide some useful insights into running this program on the new test suite? Ultimately, it would also be great if it was possible to display the coverage of the test suite as a badge on the front of the site using a tool like [Coveralls](https://coveralls.io/).

**Comment by eltmanm** [comment]
Andre Gets 8

**Comment by Andre-Bryan** [comment]
Coveralls is hooked up to the GatorGrouper repo
and i have pytest-cov ready to test and report the test suites

**Comment by Andre-Bryan** [comment]
We are using travis ci not travis pro correct?

**Comment by Andre-Bryan** [comment]
test suites return an error
![error](https://user-images.githubusercontent.com/15573401/31642943-c71e629c-b2bb-11e7-8744-49da42a8cda0.png)
