### ISSUE TITLE
Add Documentation to Show How to Run the Test Suite

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#9]
Currently, there is no test suite for this program! However, Issue #3 requests the addition of a test suite. Moreover, Issue #8 suggests that it would be a good idea to report the coverage of the test suite. It would also be great if the `README.md` file contains documentation about how to run the test suite at the command line.

**Comment by burrowss** [comment]
Let me know when you guys have documentation ready for the test suite since my group has some stuff to add for the linting that we will be adding into the test suite

**Comment by Nikki-Luoma** [comment]
There is currently a rough draft of the documentation under the i9 branch.
